.github/workflows/publish_post.yaml

github-actions: fix publish post trigger branch

---

.github/workflows/publish_post.yaml

fix typo: pipenv in CI

---

.github/workflows/publish_post.yaml

github-actions: add missing --dev flag (we need invoke to run)

---

.github/workflows/publish_post.yaml

github-actions: fix invoke build-publish task typo

---

content/extras/CNAME

config: change CNAME to conf.python.tw

---

publishconf.py

config: update siteurl to conf.python.tw

---

publishconf.py

* config
`conf.python.tw` -> `https://conf.python.tw`

config: fix siteurl config

---

pelicanconf.py

config: use customized youtube link

---

.github/CODEOWNERS

* config: add codeowners
after this setup, future pull request will be send to @pycontw/blog-admin automatically

github-actions: add codeowners

---

.github/CODEOWNERS
.gitignore
Pipfile
Pipfile.lock
pelicanconf.py

* config
* dependency
* config: setup pelican-seo
* dependency: add pelican-seo
* config: fix CODEOWNERS syntax

Add pelican seo for enhancing pycontw blog SEO

---

publishconf.py

config: in order to enable GA4, we need to use GOOGLE_GLOBAL_SITE_TAG

---

content/posts/2023-02-20-financial-report.md
pelicanconf.py
publishconf.py

* new post
* post update
* new draft
* draft update
* post metadata
* fix typo
* theme
* static page
* config
* dependency
* github-actions

2022 financial report

---

content/posts/2023-02-20-financial-report.md

post update: add space between PyConAPAC for consistency

---

content/posts/2023-03-05-gather-town-building.md

* fix typo
1. Correct the format of authors.
2. Resize pictures.
3. Change the layout.
4. fix typo.

Correct the content of post "PyCon APAC 2022 on Gather.Town"

---

content/posts/2023-11-xx-pycon-apac-2023-visiting-group.md

* new draft
draft for our PyCon APAC 2023 report

new draft: Visiting Group in PyCon APAC 2023

---

content/posts/2023-11-xx-pycon-apac-2023-visiting-group.md

* draft update
Add sections. Feel free to refine it in followup updates.

Visiting Group in PyCon APAC 2023 - add sections

---

Pipfile
Pipfile.lock
tasks.py

* dependency
* update Flex
* update pelican-plugins
* eplace isort, flake8 with ruff

Use ruff, upgrade plugins and theme

---

pelicanconf.py

* config
fix missing theme static

config: fix missing theme static

---

content/posts/2024-01-26-financial-report-2023.md

* new post
Add PyCon TW 2023 financial report

Financial report

---

.pre-commit-config.yaml
Pipfile.lock
_typos.toml

* dependency
update dependencies

dependency: update dependencies and add typo ignore word

---

.pre-commit-config.yaml

* dependency
upgrade pre-commit hooks

dependency: upgrade pre-commit hooks
